export const OLYMPIC_PICTOGRAMS_SVGS: string[] = [
  '3x3_Basketball.svg',
  'Rugby.svg',
  'Archery.svg',
  'Shotgun.svg',
  'Athletics.svg',
  'Skateboarding.svg',
  'Badminton.svg',
  'Softball.svg',
  'Baseball.svg',
  'Sport_Climbing.svg',
  'Basketball.svg',
  'Sprint.svg',
  'Beach_Volleyball.svg',
  'Surfing.svg',
  'Boxing.svg',
  'Swimming.svg',
  'Diving.svg	',
  'Table_Tennis.svg',
  'Fencing.svg',
  'Taekwondo.svg',
  'Football.svg',
  'Tennis.svg',
  'Golf.svg',
  'Trampoline.svg',
  'Gymnastics.svg	',
  'Volleyball.svg',
  'Handball.svg',
  'Water_Polo.svg',
  'Hockey.svg',
  'Weightlifting.svg',
  'Marathon_Swimming.svg',
  'kata.svg',
  'Rhythmic.svg',
]

export const ORDERED_OLYMPIC_PICTOGRAMS_SVGS: string[] = [
  'Softball.svg',
  'Football.svg',
  'Diving.svg',
  'Rhythmic.svg',
  'Trampoline.svg',
]
